plugins {
    alias(libs.plugins.android.library)
}
apply from: "../../common.gradle"

android {
    namespace "de.danoeh.antennapod.ui.notifications"

    defaultConfig {
        vectorDrawables.useSupportLibrary false
        vectorDrawables.generatedDensities = ["xhdpi"]
    }
}

dependencies {
    implementation project(':storage:preferences')
    implementation project(':ui:i18n')

    implementation libs.androidx.core
}
